### ISSUE TITLE
Plain password authentication failing

### ISSUE THREAD

**Issue by cloudtestsoftware** [htmlgraphic/Mail-Server#10]
Hi,
I was trying to test this docker instance with plain password. However, when I am trying to login using a java client program in port 587, I am getting 

javax.mail.SendFailedException: Sending failed;
  nested exception is:
	class javax.mail.MessagingException: Could not connect to SMTP host: mail.bidcrm.com, port: 25;
  nested exception is:
	java.net.ConnectException: Connection timed out (Connection timed out)
	at javax.mail.Transport.send0(Transport.java:218)
	at javax.mail.Transport.send(Transport.java:80)
	at com.bidcrm.data.test.TestEmail.sendEmail(TestEmail.java:95)
	at com.bidcrm.data.test.TestEmail.main(TestEmail.java:47)

After I run from command line to connect to my instance using my password I am getting this message

 EHLO -HP-Pavilion-Notebook
<~  250-imap-test.htmlgraphic.com
<~  250-PIPELINING
<~  250-SIZE 10240000
<~  250-VRFY
<~  250-ETRN
<~  250-AUTH PLAIN LOGIN
<~  250-ENHANCEDSTATUSCODES
<~  250-8BITMIME
<~  250 DSN
 ~> AUTH LOGIN
<~  334 VXNlcm5hbWU6
 ~> bm8tcmVwbHkyQGJpZGNybS5jb20=
<~  334 UGFzc3dvcmQ6
 ~> QmlkQ1JNMTIzSw==
<~* 535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6
 ~> AUTH PLAIN AG5vLXJlcGx5MkBiaWRjcm0uY29tAEJpZENSTTEyM0s=
<~* 535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6
*** No authentication type succeeded
 ~> QUIT
<~  221 2.0.0 Bye
=== Connection closed with remote host.

**Comment by gegere** [comment]
Hello @cloudtestsoftware this build is setup for an IMAP connection using port 143. Port 587 is used for securely relaying SMTP email. Give it another try and I'll be quick to respond if you still have issues.
