### ISSUE TITLE
mx record 

### ISSUE THREAD

**Issue by SaeidB** [htmlgraphic/Mail-Server#12]
hi  ,

where should i set my domain mx record ?

**Comment by gegere** [comment]
@SaeidB within your DNS server. Who provides the DNS from your domain?

**Comment by SaeidB** [comment]
> @SaeidB within your DNS server. Who provides the DNS from your domain?

i got domain from hostinger and i setup for ns on cloudflare,

what address should i set ,in mx setting in cloudflare

**Comment by SaeidB** [comment]
> @SaeidB within your DNS server. Who provides the DNS from your domain?

i can see imap-server in docker ps , but i think i should set mx in cloudflare , so what information should i set in cloudeflare mx ?
its in default mx.hostinger..... but i should change it , right ?

**Comment by SaeidB** [comment]
Hello


Sorry, Still waiting  !

**Comment by gegere** [comment]
Maybe this will help: [read more](https://developers.cloudflare.com/dns/manage-dns-records/how-to/email-records/)
