### ISSUE TITLE
Create a docker-compose.yml file for complete stack build

### ISSUE THREAD

**Issue by gegere** [htmlgraphic/Mail-Server#3]

**Comment by prologic** [comment]
:+1:

**Comment by gegere** [comment]
Completed, ref: 28eb360348ff28768423fd8d866b3a2d090b04bc

**Comment by prologic** [comment]
Nice work; I'll try it out :) I should just be able to:

``` #!bash
git clone https://github.com/htmlgraphic/Mail-Server.git
docker-compose up-d
```

Right? :)

**Comment by gegere** [comment]
Yes, but small correction.

```
git clone https://github.com/htmlgraphic/Mail-Server.git
docker-compose up -d
```

I actually created a make file to help manage other various commands.

```
git clone https://github.com/htmlgraphic/Mail-Server.git
make
make run
```

This will in turn run a docker-compose process. There will be additional repo updates to follow.

**Comment by prologic** [comment]
Excellent I'll give it all a whirl today sometime and let you know how it all goes!
